apiVersion: v1
kind: Service
metadata:
  name: customer
  labels: 
    run: customer
spec:
  ports:
  -  port: 8081
     targetPort: 8081
     nodePort: 30002
  type: LoadBalancer
  selector:
    run: customer
