swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /tbl_customer/:
    get:
      tags:
      - tbl_customer
      description: get TblCustomer
      operationId: TblCustomerController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.TblCustomer'
        "403": {}
    post:
      tags:
      - tbl_customer
      description: create TblCustomer
      operationId: TblCustomerController.Post
      parameters:
      - in: body
        name: body
        description: body for TblCustomer content
        required: true
        schema:
          $ref: '#/definitions/models.TblCustomer'
      responses:
        "201":
          description: '{int} models.TblCustomer'
        "403":
          description: body is empty
  /tbl_customer/{id}:
    get:
      tags:
      - tbl_customer
      description: get TblCustomer by id
      operationId: TblCustomerController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.TblCustomer'
        "403":
          description: :id is empty
    put:
      tags:
      - tbl_customer
      description: update the TblCustomer
      operationId: TblCustomerController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TblCustomer content
        required: true
        schema:
          $ref: '#/definitions/models.TblCustomer'
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.TblCustomer'
        "403":
          description: :id is not int
    delete:
      tags:
      - tbl_customer
      description: delete the TblCustomer
      operationId: TblCustomerController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.TblCustomer:
    title: TblCustomer
    type: object
    properties:
      Email:
        type: string
      Fullname:
        type: string
      Id:
        type: integer
        format: int64
      Username:
        type: string
tags:
- name: tbl_customer
  description: |
    TblCustomerController operations for TblCustomer
